const APP_ACTIONS = {
  CONFIG_LOADED: 'CONFIG_LOADED'
}

const GET_USERS_ACTIONS = {
  SEND_USERS_REQUEST: 'SEND_USERS_REQUEST',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_USERS_ERROR: 'FETCH_USERS_ERROR',
  CLEAR_ALL_NOTIFICATIONS: 'CLEAR_ALL_NOTIFICATIONS'
}

export default {
  ...APP_ACTIONS, ...GET_USERS_ACTIONS,
}